sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: QtnsBKaOft+jSydz7VUrGjioAp2mEn9fHo/l2MnfcNkMGevs2FYXpUygP+MdA4o3gqtYYPdQkhkAv/PWO5QD9uSLiP2gmkSuDxBC/zaUoJ3UiEd7+kRzxMrSBA9zIUd96/RyL0nGZoY+jnEEfrVF9cOSehGZ2tko6up6VaBUNQjqRDL2gytJaht5ZcfW2gQtzHk00402gv3N6MSD4bnmLZsgeuZ9Ba4vk43X8qE0j4+Wu+Q6sywxXJYO9+K47GZxXeN0SihaVQx7/8P2lalyKE3LfA+KcNqpRcwDvvapN2jttBebs7gzDwJuwi4pYSF5ect3/fHY9CPtmwi70TQiYgb5o85/4O2faini5G+ajx9yUh7acIrvRqV6x3qdutr+vxWvKKVLChdvmCuTTvQ4HRV5/spDjh3ctNQhWAxeNrqsBjbCJoFnkRExGtwL+5v7xY6MEIxXUR3+Asrroln6GmyS7/qdsvbwhDuGUpY9KSms89IzkA/ndosItaC24e/q2jiMsmrC0LfMnDtX1fLHHP573uvvJnZgcwlhTFVaOq0fNAdr3ZK3i6JvAmW0JSFZKLEaDrdgSEaGgGSUO2nsgUckeS8AHheW14wO/EZ6yDsT93ngzXxE9Rp0dsA0j9KfsevKT4nJbrS3vul+5ZXcOoP/a40KjHKm5jwnj4gTXbg=
