sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: fypwKejQOwCmLctVlWv6yWbbiZPL5XJ0s/h3cNQ2fvmetLRWHOWgkpR2mHqz6+8Cma+UmyHneIVNhBTth3q+7aP9xqvGQuHJ5zL0EoyNpoHzCDVnRN2ss7JQ+zPotc5qv5ucjCM0PX1H+E+57Y8rN0VSKEXaJohJyKwd5AW3oktl+Z3PCNIUzAUr3u+clHqIOgkqSxetY+wmBsErN/sGTgN9y32xLrGsWM/UmLECFK+fLXHmNJ4OWzvrBnTlDA3oxYPMiSw3xurWjnS/locjAbfQ9jKQ0PmTOEhqzCMEggZ5FBcs6LGzIPMhhsbwhYOlUPteRcFmwHFmpsk5haMQcTFIBwqdP5rAY9mN6tCLKG4KlbQK4DK+8Pa0eOaP6XeUl44n2QYFhiLfroklNFrWUkWDVDmtF5Q9UnUZFxN40XjlkTUep2mvOoFYE5+o5CoUALWsCeTBDopa6Mr0w6z10hQVl64WlPlempNb+dyui0sPb/b/Er7nvxeF+70r/nSJx+3g6cbFx7y5i8u3dMPPYJtGd1tDZTe1GgeGig7AI4Y9lMXxvewTLZ3E6wMjsg9W/7OLMh8Z5mUpVMjFfZoeYjcp2TZPhPFcZu+07NjtCJnqXug1gyf9HvQ4LxnznbJhyfB1gzhfxIJqwqtuxpVTGJ0cjQLXMe8DOms8oyxC3yo=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: QtnsBKaOft+jSydz7VUrGjioAp2mEn9fHo/l2MnfcNkMGevs2FYXpUygP+MdA4o3gqtYYPdQkhkAv/PWO5QD9uSLiP2gmkSuDxBC/zaUoJ3UiEd7+kRzxMrSBA9zIUd96/RyL0nGZoY+jnEEfrVF9cOSehGZ2tko6up6VaBUNQjqRDL2gytJaht5ZcfW2gQtzHk00402gv3N6MSD4bnmLZsgeuZ9Ba4vk43X8qE0j4+Wu+Q6sywxXJYO9+K47GZxXeN0SihaVQx7/8P2lalyKE3LfA+KcNqpRcwDvvapN2jttBebs7gzDwJuwi4pYSF5ect3/fHY9CPtmwi70TQiYgb5o85/4O2faini5G+ajx9yUh7acIrvRqV6x3qdutr+vxWvKKVLChdvmCuTTvQ4HRV5/spDjh3ctNQhWAxeNrqsBjbCJoFnkRExGtwL+5v7xY6MEIxXUR3+Asrroln6GmyS7/qdsvbwhDuGUpY9KSms89IzkA/ndosItaC24e/q2jiMsmrC0LfMnDtX1fLHHP573uvvJnZgcwlhTFVaOq0fNAdr3ZK3i6JvAmW0JSFZKLEaDrdgSEaGgGSUO2nsgUckeS8AHheW14wO/EZ6yDsT93ngzXxE9Rp0dsA0j9KfsevKT4nJbrS3vul+5ZXcOoP/a40KjHKm5jwnj4gTXbg=
